import { Achievement, UniversityMatch, RoadmapStep, CareerInfo } from './types';

export const initialAchievements: Achievement[] = [
  {
    id: 'ach-1',
    type: 'Technical',
    title: 'Python Certification',
    subtitle: 'Professional Certificate • Coursera / IBM',
    year: '2023',
    verified: true,
  },
  {
    id: 'ach-2',
    type: 'Leadership',
    title: 'Robotics Club Lead',
    subtitle: 'Bayview High School • Extracurricular',
    year: '2022 - Present',
    verified: true,
  },
  {
    id: 'ach-3',
    type: 'Academic',
    title: 'Math Olympiad Finalist',
    subtitle: 'National Level • Distinction',
    year: '2023',
    verified: true,
  },
];

export const initialUniversityMatches: UniversityMatch[] = [
  {
    id: 'uni-1',
    name: 'Stanford University',
    location: 'Stanford, CA',
    major: 'Computer Science',
    matchScore: 92,
    category: 'Target',
    tags: ['High Research Output', 'Top 1% Faculty'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDB_ijBAWHsZxbQqHtCWMNmmT-u3jGbts-kM4QC5WF0ReB7JlWmib2fFW-_ok1OVu2-C1zaUoEmwv-Y2nCPRADTa5tllWi5JCnvR2RJp0WK5k6lzSXJbcpOCp2VwASqieB283oR42OOv7_jDuVU4s17uuqFqKq3mvcOOLFfcGCL9WKuUdY8uPs20PzP34M0EVAI3j_8pScO2rGcFFoMtgzaD0h54WCDjzahM8oAhUjIXdEvQ-QqdD7mc2TQDwVIro2XVwVaSd8IX5cq',
    aiLogic: 'Based on your interest in Data Science and top-tier university requirements, Stanford is a fantastic target. Your A* in Physics and Math aligns well with Stanford benchmarks.',
  },
  {
    id: 'uni-2',
    name: 'MIT',
    location: 'Cambridge, MA',
    major: 'Data Science',
    matchScore: 78,
    category: 'Reach',
    tags: ['Research Tier 1', 'QS Rank #1'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDn_ke9ZHlp5uAoQZi0GB1Zp2Xe6zlTQYp0qTeqaEhwdeRMKFFHqpIdAlOfcowaXzEVLL5BIg5A7YREivWvE7R4EeSQL1ZBZfdUgGUefn6UmOILl-l66iqnZmUSpJ5_OuPKXJ2GF1CMHq6cHKficzbHpXlG2SNNhuQu2Ead5zOqIo7QBFWef0S-PTHd_5yzRJv3QgNHkzUcLZD-FuV-t_4eCt5hNV89oqd--s-Z55ibMYJabbgbeYqOQcd1CCIucLzPp_4jLcmhAmDA',
    aiLogic: 'Your A* in Physics and CS project on "Quantum Logic" perfectly aligns with MIT’s freshman research track. Financial gap covered by merit scholarship projection.',
  },
  {
    id: 'uni-3',
    name: 'NUS',
    location: 'Singapore',
    major: 'Computer Science & Business',
    matchScore: 82,
    category: 'Reach',
    tags: ['Global Leader', 'Tech Hub'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAt257BfIUY5kXrfwmfZoYI3PRPSZnTF99B5mtVvpULgLozF7Zd3yAMVZajjriizLeXYgbWrr02BarqOTChz71G4aHOJ72z_rcWNhyfZNFCfPei-lgHTKcYpSjgKokqg9ZWNyT12Qqv2JRPdSg1g4ViiU8EBMOU42ixowEL_lcRD0Sn0YLl9LqLuERc6uGaqKu0GbBV7WmbQoLmLEg0kMRFd5sKbIxy5SHGeF4EpMO8v9hrN46LTI27U3UqIXhq0PKcjXD2rzKrmbLR',
    aiLogic: 'Exceptional fit for the CS & Business double degree. Budget aligns well with ASEAN tuition grants for international applicants with your grade profile.',
  },
  {
    id: 'uni-4',
    name: 'Georgia Institute of Technology',
    location: 'Atlanta, GA',
    major: 'Computer Science',
    matchScore: 94,
    category: 'Target',
    tags: ['Strong AI Research Lab', 'Vibrant Startup Culture'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD_xBPwgTsEs9UpBEbeoQ0HB9bXd-vDma_sJRChMwMSI8Hyv_xdeTooR8xv8F6-xf6r7Ac1QVyQbcPDLRmh4uj3N6QEJJBUZAiSg_CvGpdZL9-jJWq6P2mPnMql37uX5cQ_hCheAT0pIXbtwACBoUSoi1p-MDATwV5CXjref3BwYtUsZf76p0gQHhuB5kProPiSetpElDu95lVPnoowRjwjSVNrlymiSFFmsJ1jQUzkB9jMhByLDrmbujv3eQTSaXjWlXTDD15dkq5v',
    aiLogic: 'Top choice for Computer Science. Your profile exceeds 90% of current freshman applicant benchmarks for STEM scores.',
  },
  {
    id: 'uni-5',
    name: 'Purdue University',
    location: 'West Lafayette, IN',
    major: 'Computer Engineering',
    matchScore: 98,
    category: 'Safety',
    tags: ['Top 10 Engineering'],
    image: '',
    aiLogic: 'Solid academic safety. Cost is significantly below your $40k cap with out-of-state merit aid.',
  },
  {
    id: 'uni-6',
    name: 'University of Waterloo',
    location: 'Ontario, Canada',
    major: 'Computer Science',
    matchScore: 96,
    category: 'Safety',
    tags: ['Co-op Leader'],
    image: '',
    aiLogic: 'Your CS extracurriculars guarantee admission. Co-op earnings will likely reduce total net cost to $25k.',
  },
  {
    id: 'uni-7',
    name: 'TU Delft',
    location: 'Delft, Netherlands',
    major: 'Aerospace Engineering',
    matchScore: 95,
    category: 'Safety',
    tags: ['EU Top Tier'],
    image: '',
    aiLogic: 'Competitive admission but your Math/Phys A* scores meet the strict entry requirements easily.',
  },
  {
    id: 'uni-8',
    name: 'Carnegie Mellon',
    location: 'Pittsburgh, PA',
    major: 'AI Engineering',
    matchScore: 87,
    category: 'Target',
    tags: ['AI Pioneer', 'Industry Linked'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAPNa9kalTCpA0fl7ERoONjn5V6SHelqrVZhIZ-UDyY2ShNG5NhUPBfPfz_JWG4EslCdv02fLkwJb7enAtCsXwALTjrhSruiYfe69yz5RRXKMDV99rXqEGKFBc7_bvIfeJeguYCqso5HMHqpeAP1bcDUhF9EVJfiRlsp8j3cqKt9SqIhIbMeu4xbsksrmYv4VMvZE4wEpywjnwzdDTS9FEZJW0Qt_366ks3hnjATpWtchHD9gFHXQkWY7WhNtVNm4GyxE3-PYsgRt9N',
    aiLogic: 'Carnegie Mellon’s SCS is world-renowned. Your robotics lead experience and competitive olympiad results put you in a very favorable light.',
  },
];

export const initialRoadmapSteps: RoadmapStep[] = [
  {
    id: 'step-1',
    stepNumber: 1,
    type: 'Current Status',
    title: 'Grade 12',
    desc: 'Academic records synced from portal. Predicted IB Score: 42/45.',
    status: 'COMPLETED',
  },
  {
    id: 'step-2',
    stepNumber: 2,
    type: 'Skill Up',
    title: 'Master Python & Statistics',
    desc: 'Essential for NUS DSA1101 modules. Focus on NumPy and Pandas libraries.',
    status: 'IN_PROGRESS',
    progress: 65,
  },
  {
    id: 'step-3',
    stepNumber: 3,
    type: 'Experience',
    title: 'Build a Data Analysis Project',
    desc: 'Create a GitHub repository showcasing a real-world dataset analysis (e.g., COVID-19 trends or Spotify usage patterns).',
    status: 'IN_PROGRESS',
  },
  {
    id: 'step-4',
    stepNumber: 4,
    type: 'Achievement',
    title: 'Enter Kaggle Competitions',
    desc: 'Compete in the Titanic and House Prices prediction challenges.',
    status: 'LOCKED',
    tags: ['TITANIC CHALLENGE', 'HOUSE PRICES'],
  },
  {
    id: 'step-5',
    stepNumber: 5,
    type: 'Research',
    title: 'Secure a summer research internship',
    desc: 'Top-tier applicants often have mentorship. We found 3 open slots at local tech labs matching your profile.',
    status: 'LOCKED',
    aiRecommended: true,
  },
  {
    id: 'step-6',
    stepNumber: 6,
    type: 'Portfolio',
    title: 'Finalize personal website',
    desc: 'Curate your top 3 projects. NUS admissions value clarity of communication alongside technical skill.',
    status: 'LOCKED',
  },
];

export const initialCareers: CareerInfo[] = [
  {
    id: 'car-1',
    title: 'Data Science',
    desc: 'Leverage statistical models and machine learning to drive business insights and predictive analytics.',
    matchScore: 94,
    salaryRange: '$110k - $175k',
    degree: 'B.S. Data Science or Stats',
    skills: [
      { name: 'Machine Learning', complexity: 'Advanced', levelSymbol: 'μ' },
      { name: 'Python Systems', complexity: 'Advanced', levelSymbol: 'Py' },
      { name: 'SQL & Warehousing', complexity: 'Moderate', levelSymbol: 'DB' },
    ],
  },
  {
    id: 'car-2',
    title: 'Quantitative Finance',
    desc: 'Design complex mathematical models to price securities and manage financial risks at scale.',
    matchScore: 98,
    aiPick: true,
    salaryRange: '$120k - $200k',
    degree: 'B.S. Math/Finance',
    skills: [
      { name: 'Stochastic Calculus', complexity: 'Expert', levelSymbol: '∑' },
      { name: 'High-Freq Systems', complexity: 'Advanced', levelSymbol: 'C++' },
      { name: 'Risk Modeling', complexity: 'Advanced', levelSymbol: 'R' },
      { name: 'Game Theory', complexity: 'Moderate', levelSymbol: 'G' },
    ],
  },
  {
    id: 'car-3',
    title: 'Econometrics',
    desc: 'Apply mathematical and statistical methods to test hypotheses and forecast economic trends.',
    matchScore: 89,
    salaryRange: '$95k - $150k',
    degree: 'B.S. Economics & Math',
    skills: [
      { name: 'Regression Modeling', complexity: 'Expert', levelSymbol: 'R²' },
      { name: 'Time-Series Analysis', complexity: 'Advanced', levelSymbol: 't' },
      { name: 'Statistical Testing', complexity: 'Advanced', levelSymbol: 'Z' },
    ],
  },
];
